<?php if (!empty($errors)) : ?>
    <div>
        <p>Une erreur est survenue :</p>
        <ul>
            <?php foreach ($errors as $error) : ?>
                <li><?= $error; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<section>
    <form action="addUser.php" method="POST">
        <div>
            <label for="prenom">Prénom : </label>
            <input type="text" name="prenom" maxlength="25" required pattern="^[A-Za-z '-]+$" title="15 caractères maximum." />
        </div>
        <div>
            <label for="nom">Nom : </label>
            <input type="text" name="nom" maxlength="30" required pattern="^[A-Za-z '-]+$" title="20 caractères maximum." />
        </div>
        <div>
            <label for="pseudo">Pseudo : </label>
            <input type="text" name="pseudo" maxlength="25" required pattern="^[A-Za-z '-]+$" title="15 caractères maximum." />
        </div>
        <div>
            <label for="email">Adresse mail : </label>
            <input type="email" name="email" maxlength="30" required title="30 caractères maximum." />
        </div>
        <div>
            <label for="password">Mot de passe : </label>
            <input type="password" name="password" maxlength="35" required title="25 caractères maximum." />
        </div>
        <div>
            <label for="password_confirm">Confirmation du mot de passe : </label>
            <input type="password" name="password_confirm" maxlength="35" required title="25 caractères maximum." />
        </div>
        <input type="submit" value="Valider" />
    </form>
</section>