<section>
    <h1>Ma liste</h1>
    <div class="listeProgrammesUser">
        <?php foreach ($listeFilmsUserAuth as $film) : ?>
            <!-- FAIRE UNE METHODE GET AVEC CONCATENATION APRES LE PHP, si pas de solution avec POST -->
            <!-- <form class="formFilm" action="deleteMovie.php" method="POST">
            <input class="supprMovie" type="submit" name="delete" value='X'>
            <ul>
                <li> -->
            <div class="formFilm">
                <a href="">
                    <p><?= $film["titre"] ?></p>
                    <!-- <p>Genre : <?= $film["genre"] ?></p>
                <p>#<?= $film["etiquettes"] ?></p>
                Renommer la classe formFilm -->
                    <img src="images/affiche.PNG" alt="">
                </a>
            </div>
            <!-- </li>
            </ul>
        </form> -->
        <?php endforeach ?>
    </div>
    <br>
    <br>
    <br>
    <br>
    <a href="modificationUser.php">Modifier les informations de mon compte ?</a>
</section>