<section>
    <form action="connexionUser.php" method="POST">
        <div>
            <label for="pseudo">Pseudo : </label>
            <input type="text" name="pseudo" required pattern="^[A-Za-z '-]+$" />
        </div>
        <div>
            <label for="password">Mot de passe : </label>
            <input type="password" name="password" required />
        </div>
        <input class="inputButton" type="submit" value="Valider" />
    </form>

    <div>
        <a href="index.php">Retour à l'accueil</a>
    </div>
</section>