<section>
    <form action="modificationUser.php" method="POST">
        <div>
            <label for="pseudo">Pseudo : </label>
            <input type="text" name="pseudo" value='<?= $_SESSION['auth']['pseudo'] ?>' />
        </div>
        <div>
            <label for="email">Adresse mail : </label>
            <input type="email" name="email" value='<?= $_SESSION['auth']['email'] ?>' />
        </div>
        <div>
            <label for="password">Mot de passe actuel : </label>
            <input type="password" name="password" />
        </div>
        <div>
            <label for="newPassword">Nouveau mot de passe : </label>
            <input type="newPassword" name="newPassword" maxlength="35" title="25 caractères maximum." />
        </div>
        <!-- Si les champs MDP Actuel et Nouveau MDP sont renseignés -->
        <?php if (isset($_POST['password']) && isset($_POST['newPassword'])) : ?>
            <!-- Si le nouveau correspond à l'actuel -->
            <?php if ($_POST['newPassword'] === $_POST['password']) : ?>
                <div>
                    <p><?= 'Le nouveau mot de passe correspond au mot de passe actuel.' ?></p>
                </div>
            <?php endif ?>
        <?php endif ?>
        <input type="submit" value="Valider les modifications" />
    </form>
</section>